spring:
#  redis:
#    host: 192.168.40.245
#    port: 6379
#    jedis:
#      pool:
#        max-idle: 8
#        min-idle: 10
#        max-active: 8
  rabbitmq:
    host: 192.168.40.244
    port: 5672
    username: guest
    password: guest
  cache:
    type: redis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.40.245:3306/cash_bus_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly
    username: admin
    password: MyNewPASS5!
#  transaction:
#    rollback-on-commit-failure: true


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.example.redisdemo.domain.entity
  mapper-locations: classpath:sqlMapper/**/**.xml

mapper:
  mappers: com.example.redisdemo.common.TkMapper
  not-empty: false
  identity: MYSQL
server:
  port: 9898

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
